In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import linear_model

In [19]:
df = pd.read_csv("prod_mizban.orders.csv", sep=',')

In [ ]:
real_data= pd.read_csv("mizban_orders.csv")

In [ ]:
real_data.head()

,date,weekday,is_weekend,orders,completed_orders,canceled_orders,active_users,restaurants,promotion
0,2026-01-01,4,0,95,88,7,420,22,0
1,2026-01-02,5,0,110,101,9,480,23,0
2,2026-01-03,6,1,150,132,18,620,24,1
3,2026-01-04,7,1,165,145,20,700,25,1
4,2026-01-05,1,0,90,83,7,410,22,0

In [20]:
df.tail(60)

,orders,completed_orders,canceled_orders,date,active_users,weekday,is_weekend
0,11,4,7,2026-02-19,9,486,False
1,6,4,2,2026-02-20,5,219,True
2,7,3,4,2026-02-21,4,202,True
3,10,1,9,2026-02-22,4,267,False
4,37,11,26,2026-02-23,12,273,False
5,8,4,4,2026-02-24,6,174,False
6,12,4,8,2026-02-25,6,190,False
7,22,8,14,2026-02-26,10,129,False
8,5,3,2,2026-02-27,2,119,True
9,3,0,3,2026-02-28,3,117,True
10,5,1,4,2026-03-01,4,125,False
11,7,2,5,2026-03-02,5,139,False
12,1,0,1,2026-03-03,1,148,False
13,11,2,9,2026-03-04,9,1061,False
14,4,1,3,2026-03-05,3,823,False
15,7,3,4,2026-03-06,5,696,True
16,4,1,3,2026-03-07,4,673,True
17,24,4,20,2026-03-08,10,637,False
18,7,6,1,2026-03-09,6,699,False
19,18,7,11,2026-03-10,12,703,False
20,12,3,9,2026-03-11,8,509,False
21,5,3,2,2026-03-12,5,498,False
22,5,3,2,2026-03-13,4,567,True
23,15,3,12,2026-03-14,7,490,True
24,20,5,15,2026-03-15,9,482,False
25,54,10,44,2026-03-16,25,321,False
26,183,19,164,2026-03-17,57,1067,False
27,44,12,32,2026-03-18,29,487,False
28,59,17,42,2026-03-19,36,563,False
29,39,14,25,2026-03-20,22,384,True
30,39,16,23,2026-03-21,31,385,True
31,31,14,17,2026-03-22,20,331,False
32,18,11,7,2026-03-23,9,325,False
33,12,2,10,2026-03-24,6,335,False
34,38,10,28,2026-03-25,21,385,False
35,34,12,22,2026-03-26,19,273,False
36,13,5,8,2026-03-27,8,244,True
37,15,4,11,2026-03-28,9,256,True
38,26,6,18,2026-03-29,11,367,False
39,16,1,14,2026-03-30,6,378,False