In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv("../newCourse/mizban_orders.csv",index_col=0)

value_count= df[["orders"]].value_counts()
df["value_count"]= value_count

df.head(2)

,weekday,is_weekend,orders,completed_orders,canceled_orders,active_users,restaurants,promotion,value_count
date,,,,,,,,,
2026-01-01,4,0,95,88,7,420,22,0,NaN
2026-01-02,5,0,110,101,9,480,23,0,NaN

In [3]:
X = df.drop("orders", axis=1)
y = df[["orders"]]
y

            orders
date
2026-01-01      95
2026-01-02     110
2026-01-03     150
2026-01-04     165
2026-01-05      90
2026-01-06     100
2026-01-07     105
2026-01-08     115
2026-01-09     130
2026-01-10     170
2026-01-11     180
2026-01-12      95
2026-01-13     105
2026-01-14     110
2026-01-15     120
2026-01-16     140
2026-01-17     185
2026-01-18     195
2026-01-19     100
2026-01-20     110
2026-01-21     115
2026-01-22     125
2026-01-23     145
2026-01-24     190
2026-01-25     200
2026-01-26     105
2026-01-27     115
2026-01-28     120
2026-01-29     130
2026-01-30     150
2026-01-31     200
2026-02-01     210
2026-02-02     110
2026-02-03     120
2026-02-04     125
2026-02-05     135
2026-02-06     155
2026-02-07     210
2026-02-08     220
2026-02-09     115
2026-02-10     125
2026-02-11     130
2026-02-12     140
2026-02-13     160
2026-02-14     220
2026-02-15     230
2026-02-16     120
2026-02-17     130
2026-02-18     135
2026-02-19     145
2026-02-20     165
2026-02-21     230
2026-02-22     240
2026-02-23     125
2026-02-24     135
2026-02-25     140
2026-02-26     150
2026-02-27     170
2026-02-28     240

In [ ]:
def split_data(X, y , test_size=0.2, randome_state=42):
    
    random_indeces = np.random.permutation(len(X))
    
    test_set_indeces=  int(len(random_indeces) * test_size)
    
    train_size_indeces= random_indeces[test_set_indeces:]
    test_size_indeces=  random_indeces[:test_set_indeces]

    X_train, X_test= X.iloc[train_size_indeces], X.iloc[test_size_indeces]
    y_train, y_test= y.iloc[train_size_indeces], y.iloc[test_size_indeces]
    
    return X_train, X_test, y_train, y_test
split_data(X,y)