In [1]:
import numpy as np
import pandas as pd
from datetime import date, datetime

In [ ]:
df = pd.read_csv("House.csv")
df.head()

In [ ]:
df["capital_location"]= df["Location"].map(lambda x:x.upper())
df["mean"]= df["Price"].mean()

today= date.today()
df["age"] = today.year -  df["YearBuilt"] 
df.head()

In [ ]:
df2 = pd.read_csv("tested.csv")
df2.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
df2["Age"]= df2["Age"].fillna(df2["Age"].mean())
df2.tail()

In [ ]:
# maping sex with 1 and 0 
 
mapping= {
    "female":0,
    "male":1,
}

print(len(df2))
df2["Sex"]= df2["Sex"].map(mapping)
print(len(df2))
df2.head()

In [ ]:
df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red"]
})

encoded = pd.get_dummies(df["Color"])

print(encoded)

In [ ]:
df = pd.DataFrame({
    "Age": [20, 25, 30, 35, 40]
})

minimum = df["Age"].min()
maximum = df["Age"].max()

df["Age_normalized"] = (
    df["Age"] - minimum
) / (maximum - minimum)

print(df)

In [ ]:
df2.head()

In [2]:
mizban= pd.read_csv("../newCourse/mizban_orders.csv",index_col=0)

mizban.head()

,weekday,is_weekend,orders,completed_orders,canceled_orders,active_users,restaurants,promotion
date,,,,,,,,
2026-01-01,4,0,95,88,7,420,22,0
2026-01-02,5,0,110,101,9,480,23,0
2026-01-03,6,1,150,132,18,620,24,1
2026-01-04,7,1,165,145,20,700,25,1
2026-01-05,1,0,90,83,7,410,22,0

In [23]:
today= date.today()
mizban["datetime"]= today
mizban["datetime"] = pd.to_datetime(mizban["datetime"])

mizban["year"]= mizban["datetime"].dt.year
mizban["month"]= mizban["datetime"].dt.month
mizban["Day"] = mizban["datetime"].dt.day
mizban["Weekday"] = mizban["datetime"].dt.day_name()
mizban = mizban.drop(columns=["orders"])
mizban.head()

,weekday,is_weekend,completed_orders,canceled_orders,active_users,restaurants,promotion,datetime,year,month,Day,Weekday
date,,,,,,,,,,,,
2026-01-01,4,0,88,7,420,22,0,2026-05-31,2026,5,31,Sunday
2026-01-02,5,0,101,9,480,23,0,2026-05-31,2026,5,31,Sunday
2026-01-03,6,1,132,18,620,24,1,2026-05-31,2026,5,31,Sunday
2026-01-04,7,1,145,20,700,25,1,2026-05-31,2026,5,31,Sunday
2026-01-05,1,0,83,7,410,22,0,2026-05-31,2026,5,31,Sunday

In [29]:
print(len(mizban))

59

In [30]:
mizban= mizban.drop_duplicates()
print(len(df2))

print(len(mizban))

418
59